# Generated by Django 5.0 on 2023-12-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcionario', models.CharField(max_length=80)),
                ('matricula_funcionario', models.IntegerField()),
                ('telefone', models.CharField(max_length=80)),
                ('funcao', models.CharField(max_length=80)),
                ('setor', models.CharField(max_length=80)),
                ('dataNascimento', models.DateField()),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
