# Generated by Django 4.2.2 on 2023-12-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('endereco', models.CharField(max_length=80)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
